/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#ffffff",
        "secondary-fixed-dim": "#ccd7d5",
        "on-secondary": "#f0fbf9",
        "on-error-container": "#752121",
        outline: "#757c7d",
        "tertiary-dim": "#485653",
        "on-surface-variant": "#5a6061",
        "surface-container-highest": "#dde4e5",
        "surface-container-high": "#e4e9ea",
        "secondary-dim": "#4b5554",
        background: "#f9f9f9",
        "inverse-surface": "#0c0f0f",
        "on-tertiary": "#edfcf8",
        "primary-dim": "#535252",
        surface: "#f9f9f9",
        "on-surface": "#2d3435",
        "on-secondary-fixed": "#374140",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#d4dbdd",
        "tertiary-container": "#e7f7f3",
        primary: "#5f5e5e",
        "inverse-on-surface": "#9c9d9d",
        "secondary-fixed": "#dae5e3",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#faf7f6",
        "surface-container": "#ebeeef",
        "on-tertiary-fixed": "#3e4c4a",
        "tertiary-fixed-dim": "#d9e9e5",
        "primary-fixed-dim": "#d6d4d3",
        "surface-tint": "#5f5e5e",
        "on-secondary-fixed-variant": "#535e5c",
        "surface-container-low": "#f2f4f4",
        "outline-variant": "#adb3b4",
        "on-error": "#fff7f6",
        "surface-variant": "#dde4e5",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-container": "#505f5c",
        "on-primary-fixed": "#403f3f",
        "error-dim": "#4e0309",
        "tertiary-fixed": "#e7f7f3",
        "on-primary-fixed-variant": "#5c5b5b",
        "on-background": "#2d3435",
        "secondary-container": "#dae5e3",
        secondary: "#576160",
        "error-container": "#fe8983",
        error: "#9f403d",
        "on-secondary-container": "#495452",
        "primary-container": "#e5e2e1",
        "on-tertiary-fixed-variant": "#5a6966",
        "on-primary-container": "#525151",
        tertiary: "#53625f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};